Model:
    CharSet: [' ', 谖, 朗, 正, 臬, 轲, 菽, 假, 定, 烜, 钱, 驻, 嬗, 伶, 瞋, 诹, 兔, 鹣, 剩, 前, 诛, 澎,
        柜, 吆, 枇, 销, 鸣, 顿, 壶, 捭, 整, 儛, 括, 圈, 掂, 讪, 庄, 萁, 幌, 赖, 承, 则, 裾, 腾, 姑, 兕, 罴,
        怦, 廓, 骚, 接, 梗, 寐, 余, 逐, 凿, 耶, 纛, 坂, 苒, 镬, 频, 绅, 旱, 沱, 儿, 憨, 吃, 佳, 垩, 哈, 揆,
        茹, 谷, 镶, 集, 屦, 停, 悟, 麕, 遬, 堪, 膝, 邑, 硁, 札, 捧, 轼, 呷, 陆, 腯, 闭, 媿, 橐, 汙, 狐, 纣,
        煮, 憔, 每, 荛, 咀, 判, 因, 兽, 臣, 昔, 筐, 拉, 卦, 珍, 访, 墺, 闩, 缰, 霸, 负, 换, 枯, 盛, 世, 谬,
        牵, 啛, 宏, 摩, 醍, 醯, 贬, 雅, 颡, 反, 硝, 金, 绸, 簪, 析, 桡, 抱, 逝, 仆, 冬, 希, 毛, 织, 袄, 瘼,
        竿, 亲, 瘠, 迎, 钺, 袷, 琯, 做, 绽, 涎, 唾, 邹, 辕, 帽, 娱, 论, 叮, 奏, 镞, 觞, 曝, 迳, 奄, 洩, 弭,
        鼍, 奇, 脏, 緌, 遏, 役, 帐, 孚, 虔, 莹, 使, 悉, 诗, 樗, 躯, 礴, 矩, 絮, 吊, 岗, 祛, 槿, 诺, 掰, 嘲,
        屐, 貎, 鼐, 库, 怀, 魉, 磐, 坟, 乘, 羼, 觜, 咈, 死, 玄, 障, 造, 鏖, 覈, 躭, 徵, 狴, 垦, 胾, 知, 巨,
        隗, 势, 旃, 鬲, 嚎, 谁, 奕, 众, 舟, 伉, 显, 韧, 楛, 偪, 渔, 环, 羯, 酗, 加, 擗, 膀, 厨, 饭, 乡, 庐,
        丈, 宕, 友, 跣, 蛛, 鳌, 胯, 列, 足, 驰, 趄, 尘, 字, 郸, 迴, 纩, 匽, 槁, 衲, 旨, 抖, 戟, 必, 敷, 旗,
        烛, 府, 漫, 揉, 哽, 颤, 叨, 鴂, 喟, 眐, 赇, 辩, 丝, 摄, 砻, 墉, 罗, 腐, 倪, 服, 惧, 异, 份, 楣, 蜩,
        砸, 敞, 戴, 畜, 醨, 愎, 佥, 缓, 蔬, 素, 善, 税, 封, 肋, 娥, 帧, 改, 孳, 分, 响, 嗟, 褐, 苴, 墁, 滚,
        箸, 淘, 茨, 萼, 牖, 鞅, 瓣, 抂, 扇, 唇, 汁, 斥, 爱, 徊, 徭, 泰, 诅, 健, 鹿, 哹, 祝, 隆, 湘, 溅, 夹,
        挨, 快, 蛊, 雩, 墓, 蜡, 暴, 遑, 故, 魅, 衔, 桶, 柑, 迍, 忻, 纳, 冤, 七, 攘, 你, 砺, 润, 法, 鼠, 拙,
        眯, 猘, 龈, 兼, 辉, 颐, 鳏, 谏, 寥, 读, 衡, 揣, 需, 壳, 晶, 坑, 屩, 勇, 婪, 龟, 擞, 伞, 劲, 鹬, 疮,
        名, 纻, 猛, 芦, 皓, 圪, 色, 扬, 猫, 觉, 阎, 璀, 黡, 眩, 詟, 幅, 腥, 辟, 惟, 首, 夔, 僽, 一, 貉, 纡,
        穴, 皦, 珪, 颓, 攒, 雍, 虹, 韦, 贩, 髭, 搓, 鞭, 骁, 粃, 餿, 关, 懂, 寅, 吏, 跄, 携, 苞, 恙, 运, 闯,
        疴, 灶, 秩, 莸, 焤, 锅, 韩, 翥, 实, 常, 诘, 欲, 岑, 贱, 嫌, 精, 且, 祧, 狞, 疯, 肮, 大, 隶, 葛, 芊,
        票, 揪, 抓, 烈, 屎, 踣, 棁, 达, 眄, 卜, 掘, 魆, 挝, 纸, 禹, 稍, 鳞, 暂, 匝, 柢, 醙, 仅, 谓, 翼, 劓,
        秽, 扭, 冷, 孙, 芍, 贰, 宥, 秤, 禳, 抚, 谋, 恩, 绶, 劻, 圃, 险, 味, 抦, 逞, 染, 浼, 宁, 泻, 胃, 富,
        拷, 炎, 瘅, 嫖, 币, 酣, 豨, 蓉, 侏, 邢, 驷, 凄, 圜, 仇, 纷, 胁, 帆, 杀, 评, 援, 潦, 哆, 坼, 勒, 锯,
        俞, 泡, 宵, 隋, 泥, 赎, 驼, 袒, 蛤, 澒, 海, 咨, 韟, 紧, 冓, 旁, 鱼, 谞, 馈, 遘, 耆, 習, 逍, 慢, 蜗,
        形, 顾, 鞫, 识, 柏, 糟, 鹊, 睫, 况, 褧, 扉, 铲, 探, 卵, 醴, 璇, 魂, 血, 璨, 饱, 舌, 迭, 盐, 潢, 蒜,
        业, 嫚, 源, 镳, 扶, 祕, 怪, 威, 鬣, 还, 靥, 囊, 程, 龙, 瑳, 跃, 窈, 蟆, 荼, 毋, 饫, 榆, 施, 狡, 傜,
        米, 超, 悦, 平, 增, 豪, 宴, 概, 挠, 方, 潭, 扎, 水, 音, 藕, 沓, 干, 瞻, 徜, 隳, 憎, 腭, 饥, 衽, 恳,
        脂, 拥, 瑱, 拿, 搦, 由, 扪, 抹, 阄, 橘, 岸, 甍, 捲, 灿, 屋, 该, 挑, 啰, 耷, 搰, 臀, 述, 倜, 膏, 百,
        着, 贤, 憾, 莩, 呴, 级, 摋, 梦, 湿, 画, 溃, 辏, 律, 穆, 率, 嫫, 郁, 啸, 吟, 揽, 槃, 辄, 冒, 诉, 伪,
        什, 晒, 危, 毳, 谀, 诈, 弥, 踏, 焚, 芳, 私, 闻, 壹, 释, 蓍, 嫦, 臂, 喃, 栏, 谙, 飍, 菹, 畸, 苦, 僵,
        侧, 闺, 钝, 喷, 澥, 涅, 岂, 卓, 哓, 韶, 胜, 蘖, 各, 熯, 荻, 史, 绑, 杯, 迁, 沮, 钵, 羽, 撮, 玑, 令,
        模, 咤, 杕, 啄, 漉, 遭, 妨, 士, 础, 冀, 悖, 割, 端, 秉, 珀, 棹, 梨, 昆, 现, 啼, 歙, 寄, 盹, 鸠, 振,
        先, 鹗, 孽, 愈, 鶗, 讲, 紊, 淆, 回, 人, 侵, 丰, 案, 工, 蓺, 杰, 騣, 想, 尸, 馀, 槽, 郎, 瑰, 旦, 彭,
        烧, 仍, 河, 隧, 钧, 覆, 絫, 轻, 侈, 癫, 鼋, 喧, 滞, 盗, 拱, 恢, 蓄, 唳, 压, 伦, 授, 葑, 责, 淮, 囿,
        杼, 胙, 困, 孤, 秀, 诱, 依, 酊, 匣, 赂, 箑, 茕, 遣, 艺, 佯, 螳, 减, 注, 智, 豕, 心, 钩, 祁, 葫, 勤,
        逆, 怆, 寸, 十, 谆, 刳, 咧, 骈, 琴, 狷, 毖, 黣, 痹, 俊, 炯, 弊, 介, 貍, 雉, 递, 瞢, 辅, 据, 芬, 钞,
        餬, 奸, 区, 崄, 右, 湛, 询, 更, 呜, 蹒, 辙, 良, 捋, 念, 鸦, 荏, 侠, 止, 直, 捉, 拽, 炭, 蜉, 搂, 偭,
        张, 配, 稀, 师, 遵, 话, 邀, 届, 罡, 閒, 酲, 弓, 含, 抉, 彝, 逋, 泇, 雾, 奋, 穗, 芙, 动, 技, 莛, 鼬,
        槊, 瞳, 侄, 恬, 桨, 芒, 胶, 腮, 亢, 俱, 莺, 囤, 殃, 浃, 羸, 搅, 孕, 苛, 铁, 薰, 悴, 粼, 驶, 叔, 吾,
        杓, 秋, 侜, 奈, 极, 抟, 选, 懈, 猿, 饰, 撦, 渡, 食, 猜, 卑, 殇, 杳, 愒, 执, 雪, 藿, 训, 劫, 三, 邮,
        暝, 距, 麞, 琱, 犀, 逊, 听, 窒, 摆, 蛔, 冁, 掣, 伍, 衿, 统, 踨, 飙, 俨, 吭, 鹤, 笨, 痌, 星, 绔, 伎,
        遥, 勿, 寓, 羝, 康, 獍, 松, 玩, 垒, 狈, 锋, 扈, 魀, 弦, 蕫, 笃, 田, 肯, 榭, 鲫, 瓮, 櫜, 官, 焮, 舐,
        炬, 篱, 属, 濊, 箪, 衅, 乖, 菘, 疾, 湔, 甚, 贮, 哭, 糊, 阗, 昭, 粹, 睁, 垛, 峙, 煞, 硗, 迷, 小, 今,
        纭, 门, 赳, 诐, 西, 穿, 予, 邦, 际, 轹, 邺, 喊, 卖, 魇, 瞎, 其, 申, 闹, 博, 归, 烬, 辍, 截, 萎, 壅,
        斛, 给, 嘉, 衰, 女, 生, 划, 艳, 枥, 坤, 萍, 奴, 茵, 棱, 基, 昙, 靴, 忭, 群, 装, 证, 泄, 碻, 挡, 补,
        鞞, 局, 京, 稂, 踕, 蓼, 埙, 肖, 妙, 晓, 筑, 唱, 劣, 戒, 协, 偕, 齧, 锣, 蜎, 遇, 捕, 朽, 枝, 顺, 鄌,
        浮, 湋, 具, 岌, 薏, 粘, 龊, 从, 界, 独, 批, 鲁, 冻, 弩, 踢, 乷, 喑, 幾, 武, 襟, 纠, 晬, 孺, 他, 槌,
        耍, 击, 恪, 蜊, 盈, 拆, 琅, 底, 投, 鹘, 鷑, 腑, 嗳, 卲, 郭, 弛, 袁, 寇, 黼, 铃, 看, 己, 勃, 墙, 叹,
        浑, 助, 轨, 筦, 日, 昊, 按, 猙, 拄, 权, 术, 扯, 冥, 苇, 欹, 原, 擅, 鴃, 旌, 跖, 浅, 涟, 穢, 摛, 毙,
        孥, 倸, 惊, 赶, 拍, 舔, 捻, 帼, 襄, 患, 古, 赁, 禾, 殁, 义, 光, 聆, 熟, 鬓, 欺, 赧, 闵, 钜, 垄, 煌,
        瓜, 咆, 鞋, 橱, 蚓, 喙, 片, 斐, 劚, 驳, 蠖, 躥, 叉, 股, 川, 剐, 严, 浓, 歧, 奉, 退, 裹, 阵, 竹, 迈,
        惭, 戳, 扁, 冈, 宇, 搽, 旋, 近, 庀, 椿, 莒, 珮, 剂, 倩, 恻, 忳, 霾, 即, 烦, 明, 蹙, 俐, 缭, 帜, 曳,
        疥, 弸, 檀, 皂, 荣, 花, 埒, 蠡, 庖, 耸, 绨, 兴, 矣, 估, 守, 辨, 菁, 鸮, 榷, 牙, 么, 逑, 潘, 隽, 早,
        皎, 蹄, 阿, 铗, 亨, 雷, 晋, 览, 钟, 媮, 辬, 楹, 恑, 当, 蝼, 塌, 畔, 捏, 墨, 抶, 缛, 呈, 睹, 餸, 胝,
        壸, 屁, 拘, 颦, 佐, 构, 幄, 纱, 货, 舵, 庶, 佹, 力, 喻, 纵, 非, 斫, 耳, 宿, 阖, 蛰, 宪, 弄, 面, 比,
        咫, 嗔, 诫, 制, 翱, 用, 逶, 黠, 塔, 镂, 赦, 邻, 嗒, 饷, 千, 惕, 语, 鮠, 拖, 肩, 稼, 绕, 珑, 挢, 束,
        尹, 医, 丁, 骇, 衫, 膻, 颊, 兮, 阬, 长, 囫, 度, 冲, 鄐, 胸, 菊, 咬, 酬, 眈, 妥, 宽, 帢, 邯, 爆, 然,
        帷, 疣, 香, 忠, 貌, 掊, 热, 落, 致, 忍, 斯, 旰, 陋, 鬵, 党, 融, 狭, 黻, 闇, 耀, 胎, 淡, 召, 烽, 拦,
        竦, 獐, 铅, 鼻, 八, 讫, 婷, 颂, 咎, 悍, 到, 轫, 撑, 林, 谔, 渠, 播, 伐, 祟, 澜, 睍, 婚, 州, 尚, 瞓,
        姬, 筝, 醐, 择, 堂, 殽, 桥, 姜, 昼, 视, 觥, 诮, 榱, 哂, 省, 帘, 逛, 哗, 猬, 跪, 夸, 慝, 畒, 佗, 扣,
        芸, 喣, 丽, 呢, 窬, 贺, 枣, 媚, 恟, 佔, 惘, 睨, 插, 鸳, 襪, 须, 仄, 勉, 迥, 桃, 幺, 逃, 剜, 贻, 唂,
        茶, 颖, 噙, 蚂, 讽, 茝, 峋, 羐, 欧, 绰, 彀, 撷, 脖, 柰, 笙, 懿, 放, 訚, 睃, 兜, 溜, 密, 醎, 瑕, 麟,
        鲐, 挦, 溯, 鲍, 檐, 篲, 阯, 信, 报, 废, 拏, 刊, 卿, 敝, 质, 戏, 献, 除, 狂, 设, 瞰, 惜, 髯, 闳, 臼,
        寞, 搪, 低, 獗, 满, 边, 愧, 奥, 来, 臻, 哑, 聊, 蚤, 吮, 藄, 旷, 裼, 藜, 殖, 汇, 睬, 留, 骧, 传, 软,
        柝, 虫, 航, 扼, 儗, 裂, 玷, 瞠, 撞, 笫, 跂, 弹, 缴, 柱, 个, 厢, 辂, 奢, 透, 抠, 耽, 呶, 宰, 综, 瑜,
        贴, 浪, 笄, 败, 乍, 虻, 宠, 廷, 骑, 益, 慵, 瓠, 恭, 殍, 玺, 围, 斟, 诽, 钥, 绝, 壕, 冕, 憬, 缺, 垠,
        株, 占, 半, 朝, 铭, 啖, 捺, 葱, 忸, 安, 綦, 扛, 茧, 陂, 签, 燕, 沈, 风, 口, 液, 迂, 匀, 饬, 嬉, 场,
        喉, 敲, 简, 聒, 泼, 烁, 絜, 剧, 笔, 僧, 阑, 汾, 矢, 吹, 痕, 于, 韪, 代, 无, 荫, 符, 蹑, 颗, 沂, 踞,
        鹂, 霜, 蛾, 煦, 剥, 痰, 瑞, 辛, 泊, 侯, 妖, 竟, 牛, 亏, 径, 砲, 瘏, 綮, 唧, 澡, 幸, 铢, 帛, 垢, 诃,
        养, 邂, 柳, 媒, 吼, 畴, 阶, 俯, 兢, 篙, 蹠, 恋, 羹, 照, 蠢, 扑, 腼, 残, 埜, 跋, 鹜, 悼, 焉, 陷, 酌,
        纰, 贪, 鹄, 旺, 栎, 肥, 体, 冗, 资, 抗, 手, 搀, 篆, 磝, 伤, 准, 迩, 桀, 簟, 愚, 粝, 戈, 罔, 擂, 徙,
        砉, 嗽, 赈, 样, 惹, 坏, 企, 旎, 言, 猯, 屣, 掐, 贳, 趼, 鸥, 峭, 专, 裸, 霖, 叩, 点, 彤, 偷, 蹀, 起,
        卉, 坊, 栈, 枵, 惯, 绩, 黔, 霓, 彪, 凶, 丸, 诞, 铮, 卸, 恍, 敢, 脯, 颜, 蒙, 颿, 麻, 帚, 萧, 淑, 摔,
        墐, 差, 萃, 酉, 咻, 是, 畅, 挺, 乔, 钦, 渖, 蚊, 褱, 沤, 汰, 谲, 横, 蒲, 却, 蛮, 蛋, 牧, 竨, 替, 煎,
        哮, 遯, 细, 偶, 榫, 累, 岵, 粒, 台, 缮, 畏, 慈, 琛, 莫, 尬, 蜚, 驿, 鲂, 穉, 瑾, 悮, 驱, 诬, 跗, 喋,
        缶, 嘴, 踵, 睥, 彬, 客, 亘, 争, 俜, 誓, 转, 溪, 畀, 睛, 儆, 羊, 鞚, 枢, 丑, 练, 确, 哲, 狼, 随, 催,
        瘝, 哥, 疑, 惏, 撺, 预, 灼, 较, 泐, 忾, 卯, 蓬, 婿, 哧, 桐, 溺, 忪, 受, 闰, 鞠, 始, 断, 踖, 究, 室,
        谠, 凋, 膈, 裕, 榪, 续, 盟, 尴, 钓, 虬, 祲, 决, 详, 锉, 诸, 怕, 晌, 朴, 多, 妃, 咽, 伴, 圭, 辜, 螃,
        洞, 农, 暧, 孑, 象, 宗, 崩, 损, 仪, 待, 惬, 扰, 琚, 得, 衷, 进, 楞, 莲, 捱, 湮, 哨, 涤, 纲, 削, 膺,
        悲, 刚, 椎, 肢, 阪, 愿, 猾, 戕, 克, 梅, 婴, 漂, 乃, 崭, 毫, 恰, 裦, 黥, 懒, 洲, 逢, 伺, 翁, 驽, 懦,
        谊, 惴, 檠, 琼, 晴, 宫, 捞, 庙, 挛, 跻, 肌, 彩, 根, 委, 堑, 荆, 傻, 窗, 夷, 扮, 侃, 鸟, 教, 房, 棠,
        浴, 虞, 侪, 耕, 摸, 囵, 眦, 蓝, 珎, 勾, 爰, 坡, 弋, 躇, 没, 嗤, 牍, 提, 免, 耐, 利, 骥, 溢, 蔺, 领,
        左, 议, 次, 般, 暖, 擐, 挫, 翦, 倥, 粱, 夏, 网, 季, 后, 蔽, 馔, 辇, 费, 橡, 燎, 嫡, 监, 妓, 揎, 蚁,
        焌, 諠, 鹭, 晏, 车, 锄, 璋, 淹, 沦, 锁, 理, 罐, 舣, 胔, 糠, 牡, 穰, 瞵, 胞, 财, 幼, 栉, 髓, 乙, 剿,
        郄, 参, 拒, 鳄, 黾, 扒, 萱, 繁, 寤, 佛, 刈, 慰, 樊, 板, 浉, 砠, 过, 簇, 媠, 跟, 殪, 纂, 约, 县, 辘,
        作, 牝, 徧, 壮, 刃, 熹, 刽, 栖, 至, 粪, 妾, 巷, 射, 黯, 捐, 蛀, 陈, 噎, 馐, 防, 童, 填, 凡, 匹, 竞,
        担, 丛, 棋, 箱, 奚, 掞, 箫, 槛, 萤, 洛, 鹞, 猱, 恣, 渎, 匿, 哩, 檄, 噬, 慴, 褴, 朔, 傯, 讷, 督, 壁,
        稳, 椟, 才, 咸, 猣, 雠, 何, 鹓, 坷, 臆, 庭, 玠, 惩, 酷, 绾, 韵, 矗, 龇, 郡, 衍, 犯, 姣, 鸾, 窝, 讼,
        孔, 机, 蜀, 腿, 经, 空, 荟, 撅, 尊, 弈, 厕, 崇, 伙, 彘, 寡, 诤, 俏, 嬴, 啮, 掼, 姻, 敦, 鸢, 骐, 郑,
        跚, 篇, 对, 混, 拊, 愁, 樽, 向, 巡, 吐, 瑶, 被, 筋, 葭, 筠, 藏, 榻, 循, 徬, 鲽, 刨, 鲜, 徂, 蕙, 陬,
        渴, 敖, 北, 朱, 盂, 翩, 麾, 兆, 咒, 唃, 靦, 滂, 粥, 搏, 卬, 搯, 踧, 触, 雄, 鲠, 在, 铸, 蚀, 菜, 鹅,
        高, 纨, 秣, 寂, 崛, 歹, 殷, 蔼, 篮, 籵, 剪, 已, 尨, 抬, 壑, 毁, 碑, 忿, 敛, 与, 舍, 内, 示, 态, 绪,
        忙, 剑, 砂, 误, 珂, 眺, 嬛, 跨, 望, 迤, 抵, 堦, 品, 缤, 饵, 船, 鞍, 既, 缨, 立, 浸, 忺, 羖, 鲵, 歉,
        盎, 偏, 恼, 漓, 霁, 炰, 剸, 僝, 魑, 猥, 轸, 餧, 虑, 阳, 马, 垂, 彻, 券, 亩, 园, 容, 闷, 亹, 帏, 陌,
        涓, 纚, 些, 簧, 志, 征, 贷, 甄, 淫, 鹏, 锷, 镀, 妆, 粮, 僻, 煽, 髀, 道, 裤, 亿, 忆, 壬, 鲈, 醮, 缉,
        彦, 忌, 轮, 木, 聋, 惑, 添, 撩, 焕, 谄, 吷, 皆, 夕, 屠, 旄, 愬, 消, 凑, 覃, 烂, 瘦, 卮, 瑚, 筌, 搘,
        拣, 饲, 佼, 瓞, 哉, 茂, 计, 堆, 骸, 嗥, 濯, 飡, 踷, 雌, 辔, 缠, 虽, 牲, 店, 杷, 衣, 临, 誉, 碧, 搜,
        炉, 仓, 骀, 宙, 梵, 毒, 棼, 唅, 烹, 歇, 搬, 瓯, 策, 叶, 浆, 昬, 派, 湾, 蝇, 妈, 春, 柚, 巇, 螓, 猦,
        层, 布, 咂, 爬, 滓, 塑, 几, 搕, 茁, 踅, 脣, 斑, 麦, 腔, 吝, 标, 藤, 禧, 突, 阒, 翕, 社, 妍, 蠙, 嚼,
        售, 疚, 侔, 儒, 骏, 走, 劝, 鼙, 仑, 霍, 囹, 蛙, 悔, 渣, 啬, 轰, 隔, 炒, 叙, 胡, 效, 零, 怵, 仗, 元,
        亮, 伥, 操, 座, 磬, 痡, 罍, 旂, 磔, 礼, 筲, 箦, 疗, 砚, 暍, 癖, 泛, 完, 全, 婀, 宋, 艰, 默, 绘, 驾,
        楚, 棒, 珠, 切, 搔, 宣, 赤, 摽, 粲, 坚, 粗, 渝, 功, 卫, 谣, 僭, 男, 挟, 屡, 剚, 焯, 沛, 格, 裙, 贡,
        菩, 诨, 忑, 脔, 绛, 弃, 捰, 汝, 蹴, 价, 恠, 帙, 算, 垣, 阻, 梢, 拳, 嘻, 茅, 懵, 鸱, 熊, 毅, 缈, 驺,
        虢, 沲, 刓, 裨, 短, 匠, 岿, 获, 嫁, 歃, 噱, 遂, 昃, 翘, 章, 节, 哀, 呿, 卻, 宛, 澹, 波, 书, 贵, 了,
        擦, 鹪, 偃, 渑, 东, 浊, 猝, 栋, 毡, 绂, 冰, 嫂, 弯, 赅, 青, 白, 筵, 刿, 自, 讬, 舛, 骛, 间, 取, 将,
        雕, 镫, 礲, 贝, 颔, 堕, 秘, 眇, 骋, 耙, 及, 潼, 掩, 暄, 怔, 诳, 存, 月, 枉, 皇, 佞, 哼, 讥, 浦, 熔,
        犹, 蟒, 豫, 相, 湃, 砾, 似, 箓, 化, 拐, 怿, 趑, 树, 莞, 包, 呻, 斠, 笼, 杖, 培, 沸, 嗓, 弢, 谤, 仞,
        篝, 豺, 踟, 银, 药, 坌, 诪, 醇, 猊, 谗, 孜, 潜, 折, 歠, 跎, 涧, 考, 曰, 央, 椽, 噁, 瞧, 种, 饩, 秒,
        钻, 缄, 磋, 愣, 盱, 裳, 找, 天, 鹃, 逭, 岭, 螺, 妻, 赞, 而, 砌, 鼎, 嶙, 阮, 痔, 汀, 淬, 电, 腆, 鹦,
        脸, 俗, 缝, 羔, 羚, 祷, 訾, 啻, 斨, 付, 济, 攀, 嵘, 问, 掉, 蔓, 醉, 雏, 雜, 橛, 职, 赔, 可, 闪, 住,
        惛, 侍, 号, 务, 庥, 齿, 蔻, 娲, 窕, 螫, 声, 商, 雹, 隘, 继, 飏, 辐, 鉴, 徐, 绌, 拈, 易, 营, 涣, 镊,
        肤, 森, 惶, 返, 战, 年, 炙, 亵, 舳, 沟, 涌, 裘, 秕, 穽, 谘, 毕, 太, 亥, 瘩, 翻, 峨, 表, 馘, 眠, 匮,
        猖, 洪, 绎, 韬, 寒, 擎, 有, 如, 眼, 裁, 轾, 贼, 蚩, 躲, 骄, 禄, 略, 褎, 狗, 泾, 鼹, 痼, 沅, 履, 雁,
        夜, 震, 怒, 傅, 丙, 痛, 采, 缩, 歬, 终, 埃, 汤, 肱, 坎, 初, 榛, 龃, 嗣, 巾, 傲, 粜, 焰, 蔚, 谩, 单,
        萏, 帝, 失, 匆, 敩, 刘, 餮, 爇, 鞘, 嗜, 簿, 歜, 洋, 罕, 沿, 譬, 崤, 埏, 黛, 共, 秾, 阅, 主, 就, 午,
        沙, 輶, 弗, 均, 熙, 爨, 俭, 乞, 函, 衮, 澌, 复, 充, 荦, 孩, 怛, 褫, 郢, 肃, 篪, 凸, 皱, 殣, 支, 磊,
        妒, 莠, 数, 蹶, 霆, 盆, 籁, 膂, 飘, 互, 宦, 舻, 陵, 抑, 铩, 吻, 亡, 窆, 鹩, 葸, 赴, 迅, 国, 甘, 饴,
        霹, 疽, 喂, 鼯, 粟, 两, 楫, 总, 楼, 贾, 祐, 鹢, 穠, 固, 美, 趣, 娓, 涕, 藋, 蝉, 悛, 清, 谢, 孝, 灰,
        澧, 贯, 匐, 苔, 苑, 救, 嫠, 磒, 忤, 毂, 描, 棺, 恸, 嘶, 时, 厘, 臭, 劭, 恒, 积, 剽, 昂, 科, 录, 蟾,
        殄, 冢, 抛, 尔, 托, 认, 朵, 悯, 髐, 娟, 踯, 漏, 轶, 攻, 麽, 蕃, 隨, 纹, 汉, 虐, 遽, 也, 否, 匡, 豢,
        岱, 捎, 疲, 躞, 埽, 帮, 跌, 饿, 赍, 火, 期, 稚, 舒, 气, 锐, 保, 违, 踩, 绥, 盘, 峡, 甫, 骊, 狎, 寻,
        贸, 渒, 楮, 延, 镝, 搥, 笠, 司, 斧, 又, 舆, 版, 刍, 馑, 眸, 採, 炸, 赐, 忡, 绠, 殊, 硎, 勺, 洌, 韫,
        绳, 惮, 姹, 观, 泪, 编, 仕, 擘, 垓, 岁, 磷, 佶, 跅, 踬, 僮, 踌, 苏, 鹰, 奔, 景, 甲, 钗, 殒, 樵, 薪,
        锵, 励, 叛, 游, 阂, 癞, 讳, 熬, 沆, 忽, 溷, 诟, 廪, 篑, 飒, 纤, 诎, 眨, 柙, 崖, 渚, 闾, 调, 扃, 倔,
        碌, 噤, 祀, 合, 褥, 榨, 渫, 副, 瀋, 魍, 遁, 瞅, 任, 杒, 汜, 芹, 五, 微, 尤, 狮, 怏, 挣, 蔑, 浡, 脚,
        删, 陟, 钿, 泯, 荤, 灭, 蒸, 类, 龌, 泣, 褛, 雳, 持, 赛, 胥, 娜, 筹, 淳, 肓, 倍, 聱, 糗, 之, 蹊, 掬,
        憝, 痂, 矮, 舜, 惝, 流, 晚, 嶂, 彰, 顶, 酸, 蜂, 氏, 幽, 缧, 睿, 钳, 变, 脆, 渐, 膑, 涨, 油, 晖, 绿,
        值, 噪, 彊, 搠, 诚, 腋, 上, 斋, 宝, 系, 聿, 打, 载, 帔, 魄, 王, 乎, 裻, 耗, 哝, 丧, 殉, 备, 辑, 帅,
        窍, 蕉, 庆, 瞩, 蜃, 南, 渟, 漆, 枕, 便, 卒, 僿, 络, 恤, 澄, 涸, 歪, 器, 帡, 串, 俛, 殢, 劬, 攞, 邪,
        柄, 砍, 轴, 糖, 二, 蹉, 鞀, 疏, 搨, 凉, 汹, 姓, 痒, 套, 不, 嗑, 慕, 镇, 薮, 谫, 伫, 吪, 别, 眢, 纶,
        军, 埋, 带, 赏, 挪, 赠, 夤, 斡, 昫, 罩, 罄, 徇, 搤, 莼, 鲸, 忮, 兀, 神, 眉, 疆, 敏, 出, 碗, 榇, 兵,
        妣, 腴, 娆, 暮, 倖, 擢, 蚌, 索, 弱, 厌, 虾, 膎, 愕, 俚, 开, 苹, 指, 窖, 弼, 拌, 偻, 濡, 并, 饕, 萌,
        尉, 芥, 熏, 攫, 德, 隐, 饔, 稽, 脐, 灵, 呼, 掷, 鸭, 额, 吠, 启, 凛, 貤, 去, 毗, 箎, 措, 蜮, 崎, 兹,
        和, 玲, 恫, 角, 呱, 廲, 慨, 嵚, 馥, 幕, 蹈, 荃, 倒, 邈, 啦, 晕, 噍, 展, 咄, 输, 酒, 靡, 跷, 旅, 窟,
        鼾, 遗, 瓦, 沾, 条, 滔, 偿, 档, 脍, 飞, 激, 凳, 眷, 惠, 抢, 映, 桑, 伯, 幙, 冠, 君, 鹑, 郐, 拗, 碎,
        彼, 醋, 赌, 恃, 佚, 周, 诲, 笥, 脾, 琶, 广, 詀, 虱, 胆, 竭, 恶, 刎, 题, 福, 呆, 锡, 滑, 哺, 吓, 阁,
        藩, 爷, 蒷, 缣, 戾, 痍, 状, 卷, 酩, 詈, 靖, 缕, 胀, 捣, 尻, 爪, 虮, 绍, 烟, 污, 锃, 矛, 缊, 械, 麈,
        漱, 谟, 见, 盼, 戛, 沧, 脉, 驴, 幡, 戮, 昨, 卧, 湖, 砭, 应, 陶, 鴗, 伈, 鲭, 尽, 荠, 仲, 砑, 绯, 岫,
        爵, 事, 乌, 赡, 莽, 若, 祇, 锥, 惫, 溓, 阆, 嘁, 纪, 优, 枚, 蒿, 腹, 讨, 修, 犁, 霞, 倨, 谨, 顷, 蔀,
        砥, 陨, 癸, 鳖, 剁, 妩, 悚, 掠, 舂, 怖, 亟, 倘, 检, 许, 勷, 脊, 降, 睦, 痺, 急, 陀, 髻, 享, 洗, 速,
        果, 磨, 竽, 叵, 劳, 斌, 苡, 逖, 骼, 聚, 脰, 例, 酾, 强, 凤, 阐, 潸, 践, 琐, 嫣, 枳, 族, 踚, 禅, 笏,
        鼓, 俑, 诏, 勘, 蝟, 窜, 六, 跑, 罅, 抭, 峰, 粉, 肺, 蟠, 竝, 倾, 鸩, 家, 蚮, 所, 键, 老, 豆, 供, 剖,
        联, 躁, 掌, 矜, 久, 察, 倡, 嘘, 蕴, 窦, 铜, 涛, 址, 湎, 篦, 芟, 隅, 中, 匕, 凝, 嘱, 诌, 佑, 往, 篷,
        豠, 遍, 潮, 习, 燔, 娴, 娑, 遮, 式, 蝎, 查, 入, 僩, 市, 绞, 朋, 眶, 烘, 荒, 俩, 厥, 巧, 昏, 皮, 坍,
        散, 跬, 饐, 咋, 嚚, 耨, 盾, 腊, 螟, 唠, 斝, 欣, 糅, 睢, 性, 赜, 狠, 杜, 再, 暑, 窠, 嚅, 巢, 劘, 觚,
        骤, 丐, 身, 债, 簠, 镪, 遝, 棍, 桔, 酥, 茸, 庞, 噀, 悠, 咳, 尿, 阋, 踊, 晷, 情, 詹, 桂, 侣, 痜, 蓑,
        津, 羞, 嗫, 纮, 允, 戚, 艴, 柴, 桊, 沌, 憍, 升, 姚, 租, 账, 辀, 衾, 募, 欢, 牺, 缘, 耻, 耘, 猎, 垯,
        骆, 搡, 政, 柔, 远, 慎, 苌, 旬, 意, 塞, 锲, 讹, 峻, 抜, 背, 龚, 赘, 汗, 晨, 撙, 桴, 铤, 躺, 屺, 瞒,
        鹺, 鬼, 避, 街, 秦, 辗, 乾, 謭, 管, 觌, 唯, 怙, 席, 瞚, 量, 荜, 禽, 聩, 佩, 枿, 黄, 乱, 沁, 泱, 熳,
        惨, 笋, 岐, 蛴, 境, 鸯, 款, 弧, 伸, 粤, 蕤, 趙, 吞, 貂, 越, 笑, 昌, 温, 挚, 云, 豚, 婆, 恕, 旧, 搴,
        屑, 赫, 娇, 惸, 萨, 妁, 盖, 厚, 团, 愠, 拂, 腕, 啧, 唤, 阜, 成, 甸, 最, 缀, 慑, 庋, 晦, 琏, 杨, 锒,
        校, 努, 茗, 会, 庚, 穷, 曜, 疼, 菅, 适, 户, 罚, 齑, 移, 馆, 山, 褒, 翅, 匙, 圄, 产, 惓, 杞, 渭, 襼,
        螯, 瘁, 葵, 永, 哙, 竖, 飧, 淄, 挂, 典, 遐, 巴, 陪, 借, 颇, 敬, 孟, 测, 抄, 目, 拔, 眴, 旖, 剉, 韡,
        祜, 试, 驭, 慧, 蛟, 灾, 脱, 漕, 芷, 搭, 劖, 纬, 夫, 英, 诓, 蛇, 披, 皋, 邓, 掇, 岛, 虺, 柁, 恨, 厄,
        队, 错, 伟, 偎, 矫, 砖, 公, 洽, 潠, 俎, 瓢, 石, 涔, 僪, 殿, 莱, 铓, 枘, 惺, 涯, 怯, 圣, 瘗, 豹, 攧,
        瞶, 尖, 肘, 爽, 阡, 彗, 愓, 拓, 鄙, 衢, 锱, 倏, 它, 螂, 搑, 拾, 穣, 部, 昧, 研, 掀, 域, 说, 筚, 袂,
        钢, 顽, 畋, 锻, 文, 颠, 踪, 巘, 巍, 蕊, 瓴, 赋, 城, 踉, 拜, 记, 佻, 蚕, 硄, 撇, 墟, 凫, 褚, 峥, 交,
        厝, 堤, 猷, 拼, 迒, 送, 谐, 崕, 恇, 闲, 埠, 绣, 琢, 鲇, 藻, 姿, 扳, 村, 匍, 铎, 汩, 寮, 诣, 滴, 刻,
        笯, 讯, 窑, 菌, 屙, 怅, 特, 第, 穅, 跳, 镒, 俾, 辞, 觅, 尝, 框, 踱, 收, 侮, 澨, 告, 绷, 仁, 膳, 獠,
        呕, 癣, 办, 併, 靠, 推, 籥, 惙, 拨, 憰, 蹦, 挹, 悄, 黧, 鷇, 鲋, 怩, 汶, 坦, 麒, 袍, 尾, 斤, 衒, 梧,
        陇, 桷, 燋, 偾, 逮, 锦, 盏, 凊, 羁, 班, 鸿, 寝, 纾, 梯, 词, 症, 蜷, 澭, 赢, 俦, 脑, 锤, 审, 苗, 肉,
        刀, 琨, 釜, 楔, 梓, 翠, 瀣, 餐, 擒, 閧, 枋, 俪, 餵, 谛, 燃, 隙, 刷, 曷, 擿, 荐, 俠, 诠, 箕, 炮, 伛,
        齰, 斩, 苟, 掿, 徼, 羿, 缁, 罪, 磛, 杅, 万, 称, 綈, 囚, 徒, 苫, 旭, 蚍, 磕, 祥, 峦, 髈, 惚, 肿, 句,
        谕, 袖, 炼, 碍, 腻, 霄, 艾, 块, 睡, 叫, 董, 魔, 绫, 羡, 贞, 绁, 迫, 汪, 谭, 感, 傥, 挽, 为, 萦, 匏,
        维, 暗, 等, 犬, 答, 窥, 骖, 裵, 好, 能, 娶, 叠, 者, 撒, 同, 建, 悱, 谮, 飨, 苍, 炊, 像, 诰, 挞, 鼪,
        罢, 叟, 傫, 嚣, 泷, 敕, 雀, 胖, 控, 缎, 儋, 著, 母, 皑, 姱, 掤, 雨, 赆, 妄, 处, 举, 樯, 榡, 禀, 胼,
        趾, 绚, 穑, 幞, 龉, 斜, 忐, 晰, 悬, 针, 瞪, 岳, 卢, 硕, 蜻, 奖, 璞, 忧, 辣, 员, 瞑, 饼, 骂, 峣, 册,
        挈, 弘, 杵, 燥, 辱, 聪, 写, 尺, 锺, 位, 狖, 辽, 悭, 绊, 鬟, 袅, 蹋, 豁, 濠, 刮, 请, 沥, 舞, 盲, 铺,
        遄, 牟, 徉, 姗, 徘, 洁, 羌, 岩, 悸, 虿, 炫, 御, 趁, 鸲, 酱, 连, 浩, 课, 诡, 瘢, 坠, 鸷, 愦, 胫, 翔,
        栗, 煨, 鴆, 命, 诵, 刬, 秃, 番, 冯, 娘, 湲, 灸, 捷, 摧, 匪, 珊, 夙, 厉, 稠, 涵, 头, 悃, 滨, 泮, 饶,
        饯, 愊, 厓, 途, 把, 祚, 裔, 曦, 绵, 唐, 红, 崧, 亦, 適, 琪, 规, 齐, 馨, 架, 另, 愆, 彟, 骨, 冶, 螽,
        殚, 导, 创, 甑, 步, 息, 埴, 寨, 序, 柯, 痴, 迢, 畛, 霏, 逡, 醒, 都, 幻, 鹉, 瞬, 坐, 耿, 篡, 悌, 荡,
        剗, 噫, 驯, 箧, 曹, 稗, 裎, 兄, 父, 摇, 庸, 寰, 黮, 唉, 演, 鲤, 诿, 怡, 结, 仃, 阽, 摹, 葩, 膊, 通,
        椠, 破, 糜, 谚, 赀, 捶, 掎, 遨, 喘, 舄, 焦, 婢, 喝, 蹬, 少, 褵, 谡, 蹿, 蟹, 霎, 渊, 佣, 娼, 毓, 厦,
        沃, 滩, 梁, 魁, 槐, 拟, 禿, 跫, 牌, 阴, 轩, 劈, 怠, 蜕, 壤, 枭, 犴, 嫉, 谇, 呐, 搧, 慷, 弟, 埶, 愤,
        膘, 珥, 储, 骜, 蒹, 徨, 九, 辈, 袭, 警, 涩, 瓶, 迹, 吁, 握, 蔌, 髫, 祸, 浇, 皁, 胠, 伏, 厮, 咏, 露,
        镌, 磅, 葬, 睖, 甜, 黑, 喜, 渲, 乳, 巫, 燮, 恐, 野, 活, 俟, 逅, 泳, 膜, 棊, 民, 炳, 鼗, 牢, 泆, 疙,
        剔, 忱, 枫, 蠹, 丘, 祖, 犊, 啭, 仿, 暇, 磇, 韭, 邅, 颅, 溲, 涉, 项, 踤, 居, 谈, 凭, 附, 解, 蹲, 扫,
        翰, 憋, 吒, 夯, 悒, 阙, 澈, 候, 黩, 行, 猴, 鸡, 汲, 段, 只, 揖, 尧, 敌, 江, 玉, 猪, 叱, 猧, 睽, 迸,
        懊, 狩, 组, 戎, 思, 睐, 魃, 下, 菲, 縻, 砣, 斗, 紫, 影, 兰, 肾, 檗, 攋, 揠, 沉, 藉, 谑, 重, 育, 郊,
        挖, 嘿, 铿, 招, 瘴, 喏, 拢, 虚, 麇, 芽, 幪, 颈, 繇, 蜜, 琵, 揭, 路, 箴, 哄, 袜, 媟, 草, 哇, 龄, 馌,
        欠, 褪, 逸, 侥, 炽, 曙, 稷, 盔, 猲, 滋, 簸, 池, 肝, 床, 夭, 筛, 歼, 耦, 屹, 契, 屯, 挥, 馁, 飖, 图,
        赵, 吸, 黜, 屈, 登, 瞽, 沫, 休, 镜, 料, 怫, 抽, 坯, 狰, 嚬, 蹰, 闱, 浞, 伊, 离, 籍, 舖, 护, 本, 核,
        井, 餍, 萝, 垆, 外, 裒, 地, 忘, 拭, 稔, 濮, 棘, 追, 灯, 亭, 骗, 吱, 驹, 吕, 以, 虎, 静, 胄, 绮, 发,
        宾, 箭, 窄, 范, 喳, 觿, 摘, 凌, 衙, 摅, 刁, 愉, 阍, 缪, 鹯, 宅, 渤, 梘, 阱, 腧, 袋, 碰, 椒, 末, 沼,
        怍, 贿, 滥, 刑, 妪, 梭, 魏, 廉, 杏, 或, 仰, 真, 蹇, 纯, 刺, 子, 禁, 婑, 芝, 稊, 謷, 脩, 鬯, 买, 橙,
        偬, 验, 灌, 鼷, 深, 求, 聘, 革, 迟, 置, 杂, 囷, 肆, 轭, 趋, 泓, 排, 夺, 硬, 泗, 植, 簦, 翚, 拇, 茫,
        晃, 害, 芜, 谎, 促, 砽, 限, 屏, 丹, 戢, 渍, 院, 枷, 逼, 埳, 赃, 病, 撼, 惰, 睚, 仙, 茞, 梳, 土, 洒,
        昻, 撧, 啕, 浍, 贫, 净, 绢, 邱, 倚, 我, 印, 抃, 涂, 缥, 踽, 啜, 诋, 淋, 疵, 掖, 未, 蝶, 让, 逻, 堙,
        榜, 觑, 狸, 螗, 沐, 黍, 鹨, 吰, 饧, 瑟, 挤, 偢, 材, 妇, 华, 殆, 亚, 璧, 肴, 缚, 圆, 泉, 治, 溘, 笺,
        辰, 潇, 蹐, 嗷, 腰, 肠, 琳, 噩, 曼, 孀, 的, 铛, 线, 貊, 愀, 宜, 嘟, 吉, 嵩, 赭, 狱, 簋, 怨, 新, 媲,
        僯, 钉, 鐀, 缐, 棬, 饮, 溥, 诜, 谦, 踡, 蜓, 犒, 抔, 黏, 堵, 娉, 楷, 痈, 撕, 鉥, 四, 箔, 逾, 嫩, 怜,
        黎, 漠, 丢, 呵, 肚, 栩, 荷, 勋, 遫, 慌, 卤, 阔, 彫, 乏, 铄, 引, 李, 缟, 蒂, 枪, 要, 此, 薄, 沽, 乜,
        琦, 跛, 捩, 诒, 拯, 难, 凰, 奂, 谅, 吴, 陡, 攸, 乐, 鬻, 踔, 双, 倦, 亸, 莋, 刖, 坛, 寿, 讴, 曲, 歌,
        嵬, 窃, 抒, 躬, 臧, 渺, 物, 羲, 崟, 历, 里, 麋, 帖, 普, 掳, 傍, 学, 荧, 辖, 皲, 馋, 曾, 泽]
    ImageChannel: 1
    ImageHeight: 128
    ImageWidth: 256
    Word: false
System:
    Allow_Ext: [jpg, jpeg, png, bmp]
    GPU: true
    GPU_ID: 0
    Path: data/cwords4-phrase-mix
    Project: cwords4-phrase-large
    Val: 0.03
Train:
    BATCH_SIZE: 320
    CNN: {NAME: ddddocr}
    DROPOUT: 0.3
    LR: 0.01
    OPTIMIZER: SGD
    SAVE_CHECKPOINTS_STEP: 2000
    TARGET: {Accuracy: 0.97, Cost: 0.05, Epoch: 20}
    TEST_BATCH_SIZE: 320
    TEST_STEP: 1000
