Model:
    CharSet: [' ', 隙, 缠, 肥, 磊, 忺, 锄, 残, 鹓, 念, 匿, 到, 隨, 聱, 衅, 娉, 藩, 炫, 梅, 悲, 澈, 籁,
        动, 社, 掎, 胾, 譬, 剿, 狡, 琯, 战, 哑, 辞, 猬, 豨, 辩, 祥, 郄, 做, 锅, 娱, 锥, 出, 昔, 睬, 徐, 投,
        佻, 准, 抠, 虬, 需, 疼, 徉, 蹙, 劝, 贡, 姿, 保, 弊, 詹, 阿, 瘼, 处, 膻, 仍, 赤, 苦, 劳, 铛, 穴, 版,
        串, 婢, 励, 枝, 跗, 喜, 劭, 桡, 人, 鸥, 搕, 湛, 侪, 髐, 偎, 铲, 坤, 抹, 造, 厌, 囤, 扎, 粃, 酬, 妪,
        克, 卷, 姹, 混, 箸, 奉, 鹺, 辖, 陨, 盼, 像, 钱, 铁, 剚, 髫, 婪, 佼, 他, 嗽, 焉, 霏, 妇, 膜, 媒, 绪,
        凌, 督, 泳, 类, 瀣, 稚, 灿, 传, 诪, 夫, 蛮, 窬, 噩, 走, 槿, 料, 笺, 小, 踊, 峻, 捉, 猎, 瘗, 颊, 浓,
        沲, 琨, 恐, 芳, 丛, 诅, 虞, 稽, 律, 拄, 皁, 毅, 殉, 既, 菩, 斑, 哇, 淫, 尴, 异, 孩, 煌, 誉, 捩, 缄,
        蝟, 雨, 伙, 孽, 童, 趙, 帚, 斟, 滚, 谩, 唱, 训, 诏, 双, 谑, 猝, 槽, 循, 搦, 鼯, 陷, 掀, 踏, 窍, 酲,
        箧, 境, 献, 瞬, 稔, 啭, 猾, 幌, 耀, 恫, 戢, 诽, 檗, 撦, 具, 初, 虾, 怖, 聒, 嚼, 赅, 幪, 珂, 瑶, 声,
        濮, 娴, 囚, 柙, 坛, 掉, 馀, 嫫, 掐, 破, 坠, 迈, 苍, 雄, 鹯, 列, 淹, 助, 青, 彫, 梢, 想, 秽, 含, 朋,
        仅, 菽, 发, 猥, 脆, 溪, 貊, 儿, 葑, 螗, 阽, 么, 偾, 彩, 蚮, 速, 蜓, 穆, 全, 绎, 盖, 麻, 愚, 睐, 渍,
        糅, 禄, 络, 僝, 钩, 帢, 宕, 诮, 跣, 濯, 哧, 逛, 扶, 吪, 契, 耗, 由, 团, 轾, 岑, 坟, 惝, 荒, 朵, 瞚,
        买, 嬗, 砉, 夷, 舳, 权, 橘, 糊, 撞, 坊, 避, 著, 输, 擅, 话, 艰, 伞, 责, 钺, 搨, 什, 栎, 齰, 就, 鹗,
        皮, 闇, 萼, 脰, 次, 罪, 痌, 妨, 刑, 哺, 纩, 屎, 撕, 劖, 会, 荦, 雌, 沤, 闩, 乖, 拣, 劲, 醨, 綦, 跂,
        厦, 变, 疣, 闯, 吊, 兼, 扉, 謭, 雏, 莠, 荠, 粤, 绌, 甲, 蛙, 璞, 徊, 摇, 植, 喘, 稗, 荫, 纾, 懦, 麞,
        瘦, 洒, 星, 柁, 拐, 徼, 惕, 穰, 层, 蜕, 履, 蒂, 喃, 宫, 卲, 值, 暇, 骧, 沓, 墓, 嗟, 辬, 捎, 屦, 痔,
        怙, 捕, 逑, 鹰, 岭, 善, 殷, 屣, 毒, 蠖, 粜, 隔, 缉, 斝, 池, 膑, 砑, 恤, 槊, 商, 蚍, 箱, 砣, 干, 年,
        舐, 轶, 夕, 俦, 辅, 醒, 裎, 激, 躥, 院, 踬, 猣, 央, 舞, 殿, 饶, 奕, 瑟, 销, 恒, 懊, 屩, 攋, 鸯, 光,
        挛, 本, 貎, 瘢, 嗔, 隘, 病, 粗, 急, 蛋, 惏, 旂, 颔, 它, 矛, 飒, 颓, 哮, 集, 翰, 落, 榻, 炯, 贞, 虮,
        畅, 罄, 褱, 陀, 眨, 蠡, 洁, 囫, 札, 快, 敛, 勇, 刻, 宽, 手, 营, 骏, 印, 螂, 鴗, 韵, 吠, 榭, 抑, 萧,
        患, 拳, 箎, 渐, 徇, 核, 蹴, 刽, 爱, 挖, 翩, 付, 司, 骖, 疗, 迳, 棒, 环, 燮, 穷, 嫩, 帼, 剽, 驯, 沂,
        甄, 遁, 篮, 矮, 豠, 族, 僿, 耙, 攻, 彭, 孚, 赛, 妄, 绨, 职, 以, 黥, 槁, 穉, 枪, 皎, 两, 纨, 仞, 黠,
        麽, 汶, 庙, 甍, 唠, 枿, 谫, 垢, 艳, 理, 羿, 岂, 浸, 遐, 睿, 眶, 赞, 愊, 彬, 竨, 抜, 惓, 嫚, 忾, 捭,
        哓, 颿, 蹋, 中, 易, 毋, 屑, 措, 娼, 贩, 功, 嚣, 私, 羐, 空, 骆, 瞑, 迒, 起, 饥, 伫, 吰, 澧, 儛, 窠,
        杷, 虚, 跄, 脔, 调, 软, 禿, 淆, 耸, 痴, 黩, 辈, 肴, 龇, 荟, 脱, 迥, 貌, 蠙, 踤, 蛾, 骑, 埋, 辱, 牙,
        届, 匙, 末, 锐, 标, 贾, 螺, 蛀, 庚, 忡, 赧, 廷, 菅, 富, 屯, 遘, 鶗, 齿, 抬, 账, 覈, 悟, 珀, 枳, 舟,
        别, 原, 馐, 辔, 古, 奢, 穽, 碻, 片, 贬, 迭, 策, 沱, 湔, 舒, 差, 胫, 姓, 馆, 蓺, 鸟, 瞻, 肠, 阴, 言,
        恇, 谡, 耆, 明, 歉, 淋, 怀, 浦, 敌, 抭, 愬, 鲁, 呆, 睡, 胜, 骸, 焰, 衒, 谎, 款, 恳, 谇, 我, 擎, 仗,
        间, 单, 弢, 灭, 尺, 吼, 制, 陪, 罅, 趾, 垛, 芥, 蜊, 笔, 兹, 阡, 粼, 傍, 亵, 殽, 疲, 秉, 回, 树, 炽,
        彊, 閒, 堦, 皱, 势, 愁, 涓, 着, 扁, 魂, 甘, 魁, 簿, 渫, 艺, 跛, 蓉, 砻, 母, 儆, 猛, 朔, 挑, 邹, 逻,
        徒, 搀, 埜, 兢, 拱, 觚, 募, 沽, 式, 乷, 邀, 耽, 虺, 衣, 戈, 冓, 吮, 消, 迫, 啻, 骂, 距, 锤, 柄, 蛤,
        跷, 蹒, 肝, 贯, 捷, 咽, 浩, 锦, 郭, 仁, 诓, 愦, 迎, 曜, 合, 捣, 卢, 筑, 株, 扈, 梘, 侏, 廪, 学, 柝,
        左, 藜, 餧, 特, 故, 愆, 瑞, 唧, 沸, 碗, 膘, 竝, 睥, 婀, 狞, 惺, 椽, 劣, 挨, 泗, 蹦, 乳, 度, 触, 余,
        瘝, 幡, 酩, 遭, 揪, 侄, 迷, 规, 至, 嫖, 化, 铢, 圣, 镞, 贸, 眷, 惩, 捐, 倘, 崕, 客, 彼, 螃, 呐, 鸲,
        幙, 澄, 渺, 该, 曙, 脚, 踕, 涸, 烟, 腔, 桀, 枵, 阳, 魆, 挢, 苴, 鸩, 逞, 咸, 碰, 省, 炳, 桶, 执, 技,
        分, 陆, 稠, 缤, 乌, 皆, 例, 蔽, 滞, 彀, 飏, 怏, 弟, 诺, 贤, 徙, 蜜, 烈, 濡, 心, 鹘, 嫦, 轹, 髻, 沁,
        展, 猲, 窥, 谁, 携, 窆, 唤, 诃, 嵬, 骗, 萝, 宏, 嘿, 寸, 觜, 袷, 挂, 荤, 外, 轮, 湾, 鴆, 护, 谊, 睨,
        裦, 冰, 爰, 陌, 持, 旱, 妣, 篑, 闲, 躬, 腴, 冈, 泻, 镳, 父, 苹, 漓, 虹, 儒, 擢, 鹣, 败, 面, 蒸, 毡,
        摛, 逖, 涂, 总, 育, 俯, 琵, 墟, 枚, 俠, 暍, 雕, 盟, 敞, 席, 擿, 雁, 打, 逊, 引, 令, 戟, 拦, 篆, 丐,
        蓼, 综, 湖, 醯, 驽, 防, 涣, 业, 砸, 完, 帧, 殁, 元, 沮, 羌, 木, 歜, 纲, 樽, 秋, 蓬, 子, 乙, 胝, 琐,
        茹, 愣, 样, 队, 剜, 眯, 瑱, 匍, 聘, 局, 趋, 眇, 楮, 荐, 宣, 坡, 琚, 歼, 颈, 俗, 瞒, 饫, 腥, 巍, 焯,
        求, 天, 坎, 郸, 躲, 痈, 俑, 素, 畸, 哼, 米, 庥, 舔, 鏖, 永, 摹, 蹈, 交, 禾, 售, 酥, 欹, 捰, 圪, 录,
        孜, 愒, 萌, 荼, 开, 聆, 帛, 狸, 煮, 躭, 抢, 较, 吐, 态, 楫, 现, 讪, 姚, 鲽, 颠, 耨, 观, 吴, 硎, 忭,
        膳, 咒, 机, 零, 韧, 挹, 政, 糖, 揣, 纭, 钦, 耶, 弃, 鞅, 鞚, 笏, 湎, 伊, 怨, 筋, 蛟, 鸷, 伦, 夹, 呢,
        精, 尧, 粱, 坷, 刖, 卖, 鹉, 难, 播, 卿, 重, 税, 裘, 羁, 剐, 锣, 饼, 忌, 翘, 嗥, 臆, 摧, 醇, 铭, 聊,
        盆, 凝, 惰, 耿, 贝, 奋, 慴, 奔, 龃, 鼗, 槛, 绽, 喋, 辙, 摸, 蹿, 刊, 苏, 尸, 怍, 法, 甚, 楔, 浮, 饭,
        嫉, 犊, 韬, 酉, 噙, 咂, 疯, 恃, 桑, 肱, 镬, 湘, 呜, 猧, 鹩, 纱, 使, 塔, 航, 歪, 岵, 熯, 瞰, 柔, 惮,
        肮, 僵, 萱, 醍, 熳, 絫, 粥, 餵, 都, 伟, 赋, 悛, 噱, 诳, 供, 瞧, 匀, 斡, 范, 宥, 捱, 缥, 汤, 副, 礼,
        充, 慑, 诿, 镌, 缨, 翻, 迸, 襼, 眩, 蟠, 尿, 伴, 嵩, 尊, 螽, 郐, 倨, 谙, 桷, 殆, 泐, 埠, 缭, 馋, 毓,
        融, 瑚, 究, 地, 锒, 呿, 德, 儋, 依, 潮, 扭, 频, 力, 净, 筐, 群, 浆, 坯, 骼, 涤, 邪, 髭, 鳏, 决, 秣,
        冒, 查, 眸, 缎, 毫, 葩, 猫, 巷, 攫, 邈, 畴, 飞, 旁, 齐, 击, 拓, 馥, 楞, 麈, 葛, 愧, 审, 板, 祷, 景,
        否, 缚, 磕, 浡, 琴, 秾, 服, 近, 害, 斥, 纯, 褥, 肘, 喂, 铩, 膺, 予, 钟, 輶, 考, 镶, 脣, 行, 毗, 哭,
        赈, 睖, 卯, 庞, 腧, 玉, 擐, 鬲, 釜, 劘, 百, 欠, 硕, 骇, 牲, 膊, 北, 晴, 围, 忻, 作, 侧, 额, 益, 俭,
        除, 霞, 尖, 莛, 个, 骁, 搯, 艴, 苗, 啛, 笫, 蟹, 披, 蒷, 丰, 摩, 搘, 絜, 跎, 熹, 佞, 远, 怦, 俜, 乞,
        漆, 萨, 帮, 孟, 派, 晚, 晷, 鹜, 闻, 六, 备, 过, 网, 趼, 目, 惶, 吞, 覃, 尨, 鼾, 筌, 柜, 咏, 贻, 舍,
        杓, 谀, 荧, 蜉, 涯, 澥, 视, 军, 猱, 追, 腰, 酸, 晬, 赇, 已, 袒, 齧, 渚, 陵, 掠, 爨, 胸, 纷, 绚, 诐,
        绂, 貍, 蚤, 卒, 適, 翁, 敝, 剑, 衡, 宦, 羝, 敕, 家, 窈, 觿, 侈, 抖, 红, 渠, 寓, 刀, 刚, 笑, 汗, 唉,
        援, 歬, 剂, 烛, 蛰, 因, 蒲, 蓄, 焮, 橡, 搪, 岳, 套, 剩, 罴, 栈, 应, 魏, 宛, 鸦, 扃, 胖, 荣, 城, 挡,
        粮, 嫌, 臀, 讨, 配, 尽, 灵, 布, 粪, 火, 棺, 肃, 锷, 虐, 杕, 扒, 删, 併, 茸, 讬, 绁, 蔚, 窟, 砖, 臂,
        醐, 覆, 慌, 此, 缕, 悃, 卑, 帷, 劓, 修, 蹇, 睢, 哗, 螯, 储, 腆, 毛, 鲇, 纚, 题, 春, 幅, 遗, 铸, 等,
        牍, 劻, 械, 牖, 澒, 烹, 胙, 蔓, 憋, 菜, 伸, 寅, 屹, 弥, 徬, 帙, 冀, 魃, 圈, 咋, 蹊, 庭, 讫, 葱, 金,
        撇, 崭, 拨, 市, 辣, 稍, 辀, 坂, 炸, 铤, 勋, 佹, 而, 帅, 碑, 竽, 讽, 纡, 聚, 圆, 渒, 任, 阔, 壹, 下,
        征, 洗, 酣, 窝, 宿, 隐, 猦, 散, 辍, 魀, 翚, 霜, 药, 堤, 鞍, 寡, 鷇, 肓, 逸, 餍, 事, 蕊, 杖, 溺, 肿,
        皋, 忠, 八, 骛, 峦, 预, 栋, 暗, 崇, 砲, 韩, 诲, 娥, 缈, 閧, 厓, 烜, 世, 眢, 改, 谨, 忤, 涎, 跚, 羼,
        猖, 钜, 锵, 吁, 穣, 龙, 爇, 辟, 蹑, 俱, 叩, 二, 装, 逅, 场, 萤, 忪, 渴, 玩, 摘, 痜, 取, 亭, 秩, 养,
        告, 包, 蘖, 骊, 榷, 霄, 谬, 锻, 豫, 阪, 坌, 碧, 凤, 杳, 一, 慷, 币, 感, 娲, 工, 裾, 摆, 脂, 荏, 芹,
        镪, 怿, 噍, 贳, 丙, 胁, 负, 邢, 蹰, 忿, 俏, 蔀, 煎, 挫, 拷, 恠, 离, 庋, 珠, 戕, 魍, 犴, 彦, 给, 踉,
        酗, 轼, 娇, 赀, 泼, 茧, 烽, 凋, 腯, 阬, 阙, 虿, 嬴, 麕, 同, 始, 忙, 换, 道, 授, 呕, 蹀, 躇, 棊, 黮,
        第, 蜚, 岫, 傻, 襟, 如, 得, 通, 簋, 莒, 羲, 邦, 牵, 蹄, 边, 菹, 泣, 女, 贿, 非, 唳, 亢, 州, 洽, 凸,
        纵, 龉, 默, 朱, 室, 忑, 陋, 步, 弓, 彤, 利, 衫, 涵, 溲, 架, 叵, 档, 脩, 箭, 胼, 俾, 紫, 垣, 妾, 籵,
        谷, 艾, 组, 抉, 秤, 曰, 聿, 饔, 仓, 锺, 祁, 幞, 渤, 亿, 冯, 姗, 憎, 缟, 糟, 瞢, 偢, 裸, 蚓, 则, 遑,
        隋, 镂, 筝, 竦, 试, 入, 侃, 叠, 臻, 每, 掰, 寝, 称, 屈, 笋, 纹, 岸, 笼, 隆, 徨, 壁, 牌, 榜, 结, 戳,
        墨, 伛, 戎, 瞳, 晶, 挟, 与, 趁, 松, 勺, 龈, 瞶, 共, 王, 飧, 泡, 邂, 慎, 帆, 谮, 鹄, 酒, 诣, 昂, 禧,
        觅, 凰, 滓, 接, 瑕, 允, 炉, 葸, 傲, 甜, 猙, 迟, 嘁, 绥, 确, 沆, 衔, 睚, 悭, 盲, 参, 豁, 写, 胠, 醙,
        框, 夔, 吕, 咫, 沐, 翼, 露, 澭, 映, 万, 添, 糗, 瘁, 砠, 琶, 猪, 终, 畋, 倸, 刘, 傜, 溷, 妈, 戛, 黯,
        耘, 悸, 承, 驿, 吸, 阖, 芽, 篱, 喙, 疏, 叙, 哨, 兴, 袅, 簪, 袜, 浴, 虑, 纬, 凊, 答, 短, 祸, 罚, 啼,
        直, 甑, 刎, 孳, 溓, 翥, 描, 妃, 襪, 灼, 乘, 砍, 濊, 亮, 飙, 导, 娓, 飘, 索, 霖, 傥, 仃, 耦, 骄, 愿,
        冢, 憾, 是, 泰, 栖, 遏, 逾, 猯, 赎, 静, 撑, 焌, 衮, 忽, 厉, 满, 蜀, 黣, 虽, 痰, 掞, 切, 倡, 宗, 沃,
        诛, 刳, 憔, 抃, 蜗, 乔, 咀, 饴, 咨, 楹, 刬, 俞, 雾, 夯, 晋, 若, 惟, 婑, 昊, 矜, 仇, 游, 匪, 鼷, 瓣,
        凄, 鴂, 圄, 介, 匆, 跨, 昃, 纠, 靥, 寂, 简, 意, 扫, 阅, 宙, 菁, 算, 为, 铜, 觞, 聩, 蹬, 堪, 液, 违,
        平, 亨, 广, 哥, 壅, 倚, 彰, 警, 孝, 抄, 妻, 郡, 瓢, 惫, 斩, 搭, 弭, 擘, 醋, 乃, 蜡, 犀, 鸠, 刃, 祜,
        祕, 肋, 恼, 矣, 腊, 撼, 淮, 拂, 真, 向, 黻, 亦, 彻, 凶, 宰, 弹, 箔, 鼪, 冷, 晕, 绍, 鞘, 狂, 岛, 楣,
        赏, 绑, 玷, 格, 暂, 路, 腮, 匝, 臧, 縻, 迴, 洩, 鞞, 毁, 搜, 凿, 亚, 孑, 蒜, 闹, 棹, 瓜, 腻, 涛, 嫠,
        牟, 啸, 亩, 乍, 傅, 背, 招, 膂, 所, 图, 狭, 纂, 存, 剉, 壳, 转, 甸, 寰, 敩, 靴, 阄, 怆, 潜, 狎, 痹,
        吱, 遬, 丘, 厝, 摽, 腭, 园, 棼, 謷, 罩, 戒, 沦, 敬, 探, 载, 韫, 深, 髀, 节, 清, 嚚, 鱼, 针, 句, 婆,
        壑, 檠, 炎, 焤, 踔, 正, 排, 絮, 曳, 悠, 衲, 塑, 圭, 嘱, 屙, 铃, 吭, 髓, 椠, 遨, 府, 蝎, 磇, 各, 馈,
        延, 拘, 玄, 烘, 滑, 阍, 蛊, 耷, 咆, 茁, 葵, 楷, 惜, 炮, 磔, 殣, 优, 鲵, 神, 禁, 贱, 擦, 贺, 珎, 苞,
        阱, 拊, 拒, 噪, 溢, 踟, 燃, 寤, 绘, 溅, 柴, 廲, 鲋, 挈, 驺, 纸, 鳞, 历, 仿, 辏, 用, 隗, 漱, 剪, 薪,
        罐, 评, 旷, 歹, 臭, 扰, 饱, 识, 床, 暑, 顿, 损, 悄, 企, 级, 邺, 寐, 渭, 要, 刁, 夸, 耻, 兀, 鼙, 忍,
        啧, 胡, 掳, 蕤, 牝, 趑, 嗳, 轲, 礴, 筚, 峨, 云, 鷑, 翔, 诚, 赴, 兆, 恬, 磅, 辨, 曷, 婴, 夤, 和, 嗒,
        罗, 赶, 雍, 袭, 财, 良, 舆, 蜩, 适, 掇, 缘, 耐, 嚅, 车, 怯, 慵, 巴, 绯, 拯, 孺, 戴, 千, 瑳, 揉, 涅,
        县, 掂, 只, 汰, 驾, 绶, 盂, 辜, 啜, 容, 槌, 谏, 曲, 懒, 褪, 埳, 测, 术, 涨, 演, 询, 瓠, 寄, 讼, 簠,
        贪, 滨, 曼, 蒿, 伥, 纻, 盛, 倖, 虔, 蹉, 悱, 炒, 哝, 缪, 嘉, 墁, 放, 嫁, 属, 壕, 慕, 洲, 哆, 蕉, 谞,
        股, 鲭, 娟, 访, 捲, 墐, 漂, 礲, 逋, 媮, 马, 吒, 狐, 窕, 免, 佣, 喻, 浇, 赔, 泉, 汇, 果, 瘅, 龟, 裒,
        囿, 崛, 渲, 搬, 思, 医, 粝, 涟, 螫, 褒, 杨, 湃, 秃, 褧, 跳, 僯, 塞, 弗, 无, 疵, 刺, 嫂, 疮, 形, 幼,
        统, 逮, 鳖, 掷, 芙, 黜, 帖, 窄, 诞, 丹, 罢, 秀, 汩, 施, 瞽, 乡, 蕫, 可, 诈, 捶, 庆, 绅, 骤, 缣, 绳,
        壸, 繇, 宜, 柳, 婿, 鞋, 郁, 锱, 蚕, 柯, 热, 杞, 衢, 喷, 赜, 盹, 辰, 铄, 钓, 梵, 胔, 妁, 鄌, 岱, 许,
        瞎, 置, 唅, 苑, 饲, 竖, 豺, 催, 读, 遮, 镀, 徭, 寞, 劬, 钝, 洋, 越, 疽, 帔, 仲, 辐, 筛, 孤, 收, 庀,
        匹, 谲, 谆, 枣, 痼, 缝, 夭, 汙, 磝, 猷, 兵, 纰, 溥, 协, 谟, 亹, 凫, 右, 咬, 狰, 愤, 闰, 咎, 梧, 藤,
        绩, 闭, 搓, 之, 赃, 待, 钵, 歙, 恢, 挝, 螓, 蔼, 管, 佐, 惛, 挚, 猿, 篪, 浃, 揆, 秘, 践, 笠, 愉, 信,
        佯, 毙, 蝼, 阯, 严, 偪, 麾, 渑, 吹, 鳄, 嬉, 稳, 磬, 脖, 暖, 齑, 樊, 唐, 捞, 泓, 旋, 员, 娑, 柚, 聋,
        晨, 恰, 康, 怩, 渎, 熙, 俊, 騣, 污, 趣, 研, 呼, 攸, 好, 风, 榪, 览, 犁, 豪, 冤, 樯, 浅, 厚, 典, 怒,
        送, 龄, 跃, 移, 睃, 舻, 埒, 浍, 拢, 衷, 倪, 宵, 醮, 野, 致, 泄, 扛, 扬, 支, 惯, 舄, 断, 肢, 椿, 痒,
        葭, 磛, 榡, 恨, 食, 劈, 曝, 倜, 窑, 窖, 豢, 界, 校, 蠹, 绞, 吃, 躁, 酊, 琱, 券, 熔, 润, 吝, 茕, 硗,
        宠, 懵, 点, 狼, 哉, 况, 逆, 胥, 划, 未, 韡, 拟, 泱, 铿, 旨, 些, 蒹, 禳, 案, 诟, 怪, 盈, 竹, 觌, 裵,
        潼, 喟, 掤, 壮, 踖, 捺, 庸, 凡, 梯, 吾, 捧, 蹲, 芟, 踣, 芦, 章, 沈, 靖, 荡, 谠, 猜, 淡, 瘏, 殇, 骚,
        渔, 汹, 谚, 咳, 塌, 滋, 黎, 后, 敦, 搂, 筦, 选, 莲, 脏, 伺, 劚, 去, 束, 斠, 肖, 磋, 鹞, 皑, 祛, 诜,
        斯, 卦, 诹, 威, 曾, 谔, 浉, 超, 镒, 豚, 诸, 榛, 痛, 汉, 癖, 倍, 苟, 僭, 费, 茵, 抂, 璋, 埏, 虱, 困,
        窗, 叮, 沥, 袖, 饩, 嘘, 公, 屏, 轻, 崤, 渝, 陬, 巫, 徵, 赘, 尹, 绔, 斜, 犒, 淘, 船, 莱, 晓, 婷, 紧,
        仪, 温, 汁, 仙, 亟, 媟, 篙, 蕴, 班, 达, 黡, 隧, 榫, 飖, 提, 椟, 祚, 鸡, 挽, 乱, 堕, 顺, 麦, 歠, 膝,
        烧, 篇, 领, 望, 榱, 符, 昙, 凭, 让, 悖, 诤, 掬, 瓦, 嚎, 尝, 恑, 肩, 监, 练, 显, 崖, 缛, 号, 徧, 侯,
        表, 鬟, 寒, 忱, 嗫, 烬, 期, 佥, 驶, 董, 从, 概, 枋, 睛, 愈, 担, 琪, 煽, 亸, 讷, 獠, 胄, 唾, 摋, 阗,
        飨, 胯, 瑜, 茗, 颅, 谛, 唃, 盏, 恟, 猘, 鄐, 颐, 悚, 莹, 诎, 嶙, 蚂, 吆, 跑, 灯, 杀, 画, 乜, 漕, 橐,
        豕, 祇, 绵, 杵, 傯, 众, 芍, 隳, 欧, 踅, 缐, 吓, 撒, 讴, 峡, 疑, 唯, 石, 绸, 趄, 眈, 茞, 附, 进, 斫,
        辉, 滂, 箕, 悼, 澜, 酷, 卤, 构, 相, 莽, 赢, 勃, 踵, 焕, 弦, 钗, 议, 鬵, 簟, 陡, 侵, 徜, 苔, 蔺, 狩,
        泛, 伪, 慈, 白, 惊, 裙, 奄, 愓, 羯, 泷, 殊, 缰, 鹏, 签, 峋, 债, 镇, 怜, 鹊, 膈, 方, 铓, 蚁, 枇, 侣,
        歃, 恶, 牡, 掊, 症, 湋, 蛇, 冕, 峥, 壤, 率, 榆, 冠, 抟, 跖, 嫡, 脾, 懿, 珮, 蜃, 黛, 瞵, 姑, 怔, 芊,
        袁, 碎, 喉, 匣, 迂, 尬, 疚, 揭, 呴, 黍, 臼, 番, 蜎, 庄, 矢, 踡, 朝, 数, 绢, 跌, 幸, 侠, 伯, 还, 文,
        蜻, 钧, 鞀, 撷, 瑰, 啦, 杯, 斋, 半, 腼, 荃, 龚, 础, 抓, 沟, 陶, 赡, 阐, 旬, 瓞, 补, 枕, 奈, 酾, 窒,
        鼋, 孥, 讳, 辇, 粒, 另, 旭, 缁, 质, 党, 创, 蚌, 扳, 狱, 阒, 坐, 寨, 嘶, 扣, 癞, 屺, 猴, 山, 似, 僩,
        瘠, 妖, 认, 鹬, 匡, 倩, 折, 烂, 盗, 堑, 关, 瓶, 蛛, 疥, 畔, 嘟, 久, 铺, 柰, 垯, 喣, 弸, 褐, 饰, 村,
        痕, 鬯, 孙, 脉, 佗, 铗, 毕, 悍, 脊, 然, 砭, 拭, 扇, 井, 亡, 摔, 新, 芬, 垓, 梭, 俟, 呶, 骋, 辂, 杼,
        轩, 悮, 错, 饵, 癫, 于, 返, 琛, 靡, 兜, 赭, 弄, 罍, 壶, 芸, 楚, 鹭, 日, 丽, 熬, 冻, 眄, 证, 绠, 懂,
        啄, 掖, 朗, 禽, 俛, 刓, 冲, 论, 瓯, 镜, 訚, 玠, 抱, 项, 潠, 妙, 专, 琼, 畛, 炰, 虢, 彪, 惹, 象, 慧,
        推, 醴, 胞, 障, 建, 遥, 恋, 硝, 喧, 享, 狈, 油, 种, 簦, 苒, 粹, 斐, 函, 弛, 菲, 橱, 足, 姣, 匏, 袍,
        袂, 啬, 酱, 矫, 泯, 段, 鹨, 莸, 麒, 请, 殪, 亲, 昏, 谭, 叛, 囊, 胆, 妥, 栉, 汲, 迅, 踚, 革, 媿, 窃,
        涔, 苫, 藏, 韭, 愀, 啮, 晰, 叔, 志, 曹, 毳, 义, 腑, 澹, 戮, 泪, 织, 荆, 角, 记, 羸, 成, 夜, 阁, 肾,
        守, 瓴, 亘, 堂, 品, 设, 蜷, 桴, 今, 纳, 摄, 橛, 杜, 朽, 尤, 射, 殃, 俐, 姱, 根, 舜, 示, 馨, 头, 觥,
        鲜, 狷, 踪, 候, 饯, 穢, 雪, 带, 惸, 鼓, 秕, 芷, 萃, 效, 登, 琢, 桐, 睁, 驳, 几, 染, 啕, 凉, 奥, 握,
        肺, 剔, 诱, 的, 横, 滴, 蠢, 邑, 区, 照, 诬, 杰, 酌, 丑, 森, 汾, 湲, 扪, 黔, 棍, 联, 南, 耳, 上, 卬,
        缺, 臬, 英, 洪, 蹐, 梓, 砾, 窦, 首, 袋, 玲, 少, 妒, 恩, 撧, 哽, 狖, 银, 癣, 伶, 振, 旦, 烁, 拉, 驷,
        苇, 綮, 膏, 华, 倾, 对, 咄, 糠, 妆, 托, 吷, 怵, 莞, 川, 口, 谋, 误, 慰, 蓍, 味, 澨, 霾, 堆, 挞, 拾,
        噁, 止, 尔, 吟, 斛, 厢, 普, 削, 帏, 气, 崩, 语, 媚, 挦, 农, 漠, 知, 勒, 刮, 沛, 碌, 掼, 峣, 部, 羡,
        倒, 犬, 蟒, 犯, 睹, 闺, 咈, 暧, 梗, 畀, 掩, 诋, 敢, 电, 霁, 占, 鼹, 端, 卻, 色, 僻, 辕, 诵, 阮, 哹,
        砺, 遇, 畏, 涌, 怅, 滥, 伐, 慝, 检, 析, 膎, 檀, 楛, 浞, 弩, 邅, 锁, 十, 呻, 翦, 唂, 旖, 禀, 雩, 恸,
        钥, 批, 滩, 琳, 栏, 爽, 繁, 闳, 粟, 棘, 驻, 填, 爪, 密, 肌, 鴃, 柢, 渊, 漏, 假, 羚, 裔, 羖, 茶, 妍,
        帝, 涧, 巘, 兽, 哲, 薄, 留, 伏, 槃, 竟, 鸭, 御, 维, 脯, 褚, 峭, 歧, 申, 痂, 拜, 哂, 鲂, 缀, 娶, 傫,
        浪, 票, 踩, 骈, 邻, 寇, 培, 眦, 搰, 遽, 茂, 潦, 檄, 箑, 赆, 捏, 遍, 殄, 獍, 伈, 僮, 匐, 者, 揎, 看,
        撮, 休, 髯, 蜮, 紊, 邯, 幾, 黏, 勷, 攞, 扑, 郑, 蚩, 西, 韪, 泮, 箴, 悦, 险, 前, 霆, 计, 韶, 垂, 枭,
        努, 坼, 拌, 殖, 罕, 瞪, 馁, 房, 琏, 爷, 瞠, 扼, 搠, 羔, 骜, 哀, 夙, 弱, 搤, 里, 月, 暴, 绕, 伍, 伎,
        悒, 序, 限, 住, 諠, 燔, 炼, 踱, 江, 缩, 枷, 涕, 殢, 寻, 何, 梨, 汝, 庶, 迩, 恣, 餮, 挪, 夺, 水, 欣,
        模, 幄, 绾, 罔, 库, 基, 括, 湮, 梳, 沙, 智, 勤, 顶, 滔, 瞩, 截, 鉥, 戏, 挤, 鸱, 倥, 阋, 帡, 瘩, 妩,
        龊, 随, 锲, 俩, 馑, 斧, 恙, 忧, 腾, 贴, 痺, 祝, 虻, 剗, 韟, 钳, 屋, 翅, 褵, 嬛, 抶, 鞠, 攘, 逍, 悔,
        巡, 户, 硁, 楼, 街, 怠, 砥, 弼, 情, 溃, 谤, 乏, 衍, 漉, 材, 封, 卫, 庖, 响, 绿, 钢, 莼, 鹤, 泾, 欲,
        积, 抵, 舣, 赦, 捻, 代, 屐, 纤, 册, 旎, 呈, 灶, 般, 绊, 瞅, 鼐, 肯, 抛, 潘, 体, 抒, 痍, 胀, 杅, 腐,
        颂, 盐, 定, 寮, 轸, 竞, 最, 魑, 编, 巧, 音, 苛, 餐, 嗤, 绰, 死, 姬, 津, 璧, 媲, 莫, 椎, 卸, 棋, 峙,
        脍, 黾, 钻, 旰, 蔬, 枢, 老, 袄, 状, 沉, 惘, 被, 醉, 埶, 宪, 浼, 弘, 剁, 估, 及, 菌, 饷, 菊, 奏, 俎,
        悯, 岌, 卓, 帜, 鬣, 雹, 璨, 血, 弈, 锉, 祟, 怛, 鄙, 陂, 诰, 遫, 祖, 美, 孀, 俪, 缮, 斤, 蟆, 镝, 鸿,
        仰, 戾, 奸, 轨, 闾, 辑, 澌, 渖, 昫, 雜, 厕, 翠, 砂, 颗, 镫, 性, 鹑, 途, 坑, 拍, 轫, 谗, 宅, 榇, 熏,
        潇, 旗, 挥, 胶, 燥, 裁, 懈, 铮, 桨, 陟, 崧, 瑾, 隅, 萏, 裤, 谢, 饕, 腿, 土, 杂, 喝, 奚, 翕, 幻, 湿,
        豆, 靠, 诫, 没, 肆, 赐, 哙, 昨, 三, 碍, 隽, 茨, 裳, 鸳, 疴, 均, 擞, 畜, 躯, 鸣, 京, 珑, 叹, 魅, 僪,
        辛, 詟, 赍, 褫, 洞, 鲐, 偏, 跋, 忐, 饿, 份, 箫, 坦, 盎, 谦, 惧, 丧, 嫣, 便, 铎, 禅, 绛, 篷, 徂, 拈,
        谄, 毖, 澎, 流, 自, 裂, 愕, 扮, 闱, 栩, 埙, 递, 櫜, 帽, 判, 忘, 兰, 皓, 瞋, 鲠, 屁, 烦, 溯, 勘, 晌,
        咻, 夏, 骥, 安, 轰, 堙, 迍, 幺, 鹦, 躞, 羊, 搔, 裼, 惴, 嗜, 墺, 谅, 台, 倦, 渟, 弯, 狠, 宝, 仆, 弋,
        拔, 更, 觉, 梦, 擒, 菘, 狗, 涉, 墙, 螟, 四, 屡, 麇, 韦, 莩, 搴, 倏, 睫, 踧, 歌, 叨, 箓, 蔑, 强, 挠,
        浑, 僧, 诠, 霹, 泊, 蜂, 其, 晒, 衽, 舖, 并, 辽, 绫, 垩, 哄, 诨, 宁, 纮, 眼, 阂, 祧, 系, 长, 阑, 纛,
        馌, 跻, 餸, 抚, 搥, 渡, 鸮, 鲤, 冗, 蕃, 宾, 憨, 椒, 影, 膀, 友, 田, 停, 蔻, 偭, 挣, 卧, 垦, 彝, 瓮,
        荛, 斗, 鳌, 喳, 垒, 妓, 籥, 瘴, 迢, 绝, 绷, 绣, 阵, 饬, 迹, 彘, 霍, 昭, 阜, 割, 鼍, 畒, 赖, 臣, 微,
        剥, 抦, 字, 运, 囹, 波, 灸, 捋, 蝇, 筲, 搏, 赁, 匽, 驴, 昬, 偬, 盾, 瀋, 潢, 晖, 掣, 桃, 替, 乎, 衰,
        牛, 掿, 刈, 贷, 慨, 嗓, 颡, 临, 髈, 经, 廓, 峰, 伤, 歇, 锃, 稊, 芝, 纪, 稂, 谣, 牢, 解, 敖, 际, 暝,
        冁, 钞, 冶, 活, 鹢, 綈, 居, 蒙, 兔, 眴, 霎, 物, 榨, 诗, 忆, 揠, 嶂, 刿, 侮, 减, 资, 恻, 爵, 雳, 惭,
        筵, 埴, 揖, 拼, 啖, 鬼, 粉, 偃, 甫, 择, 辄, 闪, 牺, 眉, 慢, 偷, 晏, 佔, 务, 贮, 攀, 焦, 灰, 壬, 操,
        冥, 谕, 生, 轴, 笨, 砌, 谐, 内, 圜, 谈, 须, 爆, 耍, 馘, 汀, 且, 你, 娆, 拏, 有, 侍, 丈, 辗, 孕, 汪,
        鬻, 坚, 颖, 秦, 劫, 匠, 虫, 颤, 彗, 疾, 笃, 周, 郢, 海, 貂, 块, 箪, 耕, 迤, 赳, 才, 驭, 叶, 晦, 藄,
        喊, 拖, 时, 国, 媠, 茅, 朴, 佶, 肉, 砽, 藿, 咧, 却, 往, 高, 偶, 萎, 泥, 奇, 仑, 逃, 啰, 垆, 溜, 敲,
        抗, 丁, 皲, 增, 腋, 师, 麟, 亏, 诌, 皂, 垄, 愠, 狴, 疆, 沾, 幽, 治, 踽, 腕, 尉, 嵘, 潸, 锯, 仄, 驹,
        岩, 剸, 立, 将, 噀, 攧, 憝, 鼬, 闷, 废, 莋, 怡, 沫, 逼, 科, 纣, 迁, 埽, 巾, 宇, 珥, 健, 即, 苡, 汜,
        祀, 挺, 据, 跫, 犹, 恪, 雷, 稷, 连, 雠, 磒, 教, 怫, 季, 报, 睍, 七, 觑, 贵, 撅, 蔌, 茝, 危, 固, 憰,
        詈, 拽, 哩, 姻, 璇, 缓, 猊, 细, 在, 诘, 晃, 梁, 佑, 颜, 颇, 也, 吏, 辘, 侜, 踯, 必, 噬, 竭, 河, 嘻,
        憬, 溘, 茫, 欺, 邱, 逝, 胎, 崟, 杏, 获, 花, 噤, 毂, 述, 踌, 蛔, 复, 多, 赌, 桔, 褴, 顽, 厘, 秒, 呵,
        坏, 矗, 暮, 習, 硄, 餿, 赫, 互, 键, 听, 盱, 锡, 陇, 位, 隶, 屠, 眐, 抔, 呱, 杒, 沅, 词, 淑, 舂, 奖,
        争, 退, 找, 帐, 癸, 踷, 沌, 芜, 檐, 盘, 把, 悉, 程, 骨, 貤, 再, 拆, 跬, 薏, 衙, 缶, 尾, 丝, 篲, 纶,
        枥, 忸, 槐, 佳, 氏, 伉, 产, 囵, 彟, 婚, 岿, 藻, 脸, 偕, 枘, 租, 厄, 泇, 鼠, 稼, 勉, 巇, 簸, 祲, 驰,
        名, 见, 鮠, 萦, 悌, 升, 凑, 吉, 颦, 极, 轭, 穠, 能, 蓑, 燋, 珪, 尘, 旄, 炭, 谖, 穅, 腹, 叫, 侥, 冬,
        昌, 突, 当, 弧, 跅, 赂, 浊, 座, 鲍, 嗑, 委, 笙, 厥, 魉, 旅, 踞, 顾, 勿, 岁, 卵, 跟, 棬, 沧, 笥, 诒,
        救, 缴, 骐, 蹶, 霓, 緌, 蝶, 鲫, 荻, 旧, 廉, 驼, 聪, 草, 穗, 遝, 灾, 採, 启, 敏, 魄, 希, 貉, 注, 偿,
        己, 稀, 实, 君, 嵚, 粘, 玺, 棁, 琅, 惚, 谘, 继, 五, 蹠, 擗, 躺, 货, 巨, 岗, 踨, 娘, 掘, 匕, 粲, 借,
        桥, 拗, 恍, 斨, 鲸, 垠, 侔, 量, 缊, 藕, 阆, 卉, 常, 勾, 钉, 镊, 士, 熟, 凛, 贰, 卜, 忳, 鸢, 潭, 樵,
        摅, 男, 怕, 铅, 邮, 枉, 续, 逐, 鞫, 痡, 窜, 踢, 洌, 惠, 皇, 搅, 诡, 穿, 砚, 燕, 林, 霸, 埃, 箦, 嚬,
        整, 薰, 刍, 书, 顷, 磨, 裹, 官, 底, 飡, 兮, 奴, 狮, 佛, 问, 篝, 竿, 不, 栗, 指, 昼, 暄, 倔, 先, 爬,
        誓, 澡, 葬, 魇, 民, 兄, 尚, 麋, 炬, 枫, 萍, 蛴, 藋, 鲈, 闵, 呷, 撙, 透, 贫, 柱, 龌, 唇, 憍, 拙, 逶,
        皦, 昧, 办, 贼, 太, 靦, 厮, 蚀, 习, 柏, 条, 源, 眠, 径, 约, 矩, 帘, 惬, 压, 昆, 荜, 苌, 庐, 泽, 飍,
        殍, 嗷, 棠, 黑, 噎, 襄, 萁, 跪, 珍, 燎, 娜, 忮, 豹, 醎, 鹃, 桂, 命, 拥, 硬, 鹂, 价, 了, 咤, 詀, 糜,
        乐, 鬓, 加, 芒, 刷, 裕, 煦, 谓, 馔, 赵, 兕, 穑, 丢, 厨, 斌, 訾, 惨, 裻, 锋, 插, 饮, 俨, 漫, 舵, 黼,
        圃, 亥, 棱, 鼻, 珊, 器, 脐, 促, 刨, 郊, 嗣, 墉, 低, 控, 噫, 薮, 涩, 擂, 儗, 骀, 惙, 祐, 荷, 役, 磐,
        崎, 盔, 恕, 扯, 午, 脑, 羹, 凳, 愎, 寥, 鹪, 鼎, 主, 奂, 诉, 翱, 召, 偻, 崄, 昻, 遂, 反, 寿, 遄, 衿,
        堵, 撺, 羞, 羽, 失, 东, 魔, 焚, 蓝, 鸾, 大, 张, 煞, 攒, 瞓, 橙, 黄, 累, 坍, 采, 笯, 李, 蟾, 来, 雀,
        绮, 遣, 炊, 略, 睽, 门, 搡, 禹, 剧, 饐, 鞭, 玑, 搧, 独, 蝉, 说, 衾, 史, 尻, 樗, 鹅, 睦, 煨, 罡, 受,
        俚, 济, 九, 哈, 巢, 籍, 佩, 阶, 葫, 戚, 饧, 早, 胃, 蚊, 眺, 孔, 欢, 掌, 丸, 赠, 店, 钿, 缧, 或, 桊,
        郎, 淄, 沿, 敷, 遵, 岐, 讲, 僽, 餬, 归, 旺, 濠, 炙, 旃, 址, 渣, 课, 宋, 举, 筹, 福, 比, 又, 獐, 讥,
        香, 褛, 洛, 虎, 察, 线, 按, 篡, 叱, 殚, 笄, 簇, 阻, 详, 獗, 叉, 恭, 撩, 牧, 嘴, 叟, 博, 肚, 惑, 舌,
        鉴, 嘲, 熊, 悬, 沼, 筠, 卮, 徘, 疙, 磷, 琦, 讹, 莺, 幕, 鹿, 吻, 域, 释, 柑, 仕, 蕙, 泆, 旌, 璀, 黧,
        身, 遯, 裨, 陈, 淳, 雉, 武, 息, 震, 乾, 褎, 搽, 抽, 宴, 降, 逢, 篦, 验, 曦, 剖, 喏, 匮, 揽, 讯, 雅,
        拇, 簧, 邓, 逭, 佚, 鐀, 驱, 枯, 淬, 螳, 拿, 肤, 殒, 阎, 搑, 藉, 姜, 逡, 舛, 囷, 喑, 灌, 悴]
    ImageChannel: 1
    ImageHeight: 64
    ImageWidth: -1
    Word: false
System:
    Allow_Ext: [jpg, jpeg, png, bmp]
    GPU: true
    GPU_ID: 0
    Path: data/cwords4-phrase-mix
    Project: cwords4-phrase
    Val: 0.03
Train:
    BATCH_SIZE: 768
    CNN: {NAME: ddddocr}
    DROPOUT: 0.3
    LR: 0.01
    OPTIMIZER: SGD
    SAVE_CHECKPOINTS_STEP: 2000
    TARGET: {Accuracy: 0.97, Cost: 0.05, Epoch: 20}
    TEST_BATCH_SIZE: 768
    TEST_STEP: 1000
