Model:
    CharSet: [' ', س, ع, ٹ, ض, ڑ, غ, ژ, ظ, ق, ۂ, ص, ح, خ, چ, ج, پ, ۓ, ز, ی, ؤ, ل,
        ھ, ڈ, ذ, ے, د, و, أ, ئ, ر, ۃ, ک, آ, ں, ط, ف, ن, ث, گ, ہ, ب, ش, ا, ت, م, ء]
    ImageChannel: 1
    ImageHeight: 60
    ImageWidth: 160
    Word: false
System:
    Allow_Ext: [jpg, jpeg, png, bmp]
    GPU: true
    GPU_ID: 0
    Path: data/uchars4
    Project: uchars4
    Val: 0.03
Train:
    BATCH_SIZE: 960
    CNN: {NAME: ddddocr}
    DROPOUT: 0.3
    LR: 0.01
    OPTIMIZER: SGD
    SAVE_CHECKPOINTS_STEP: 2000
    TARGET: {Accuracy: 0.97, Cost: 0.05, Epoch: 20}
    TEST_BATCH_SIZE: 32
    TEST_STEP: 1000
